parameters:
    # Payline default config
    payline_config.merchant_id: "XXXXXXXXXXXXXX"
    payline_config.access_key: "XXXXXXXXXXXXXXXXXXXX"
    payline_config.proxy_host: ""
    payline_config.proxy_port: ""
    payline_config.proxy_login: ""
    payline_config.proxy_password: ""
    payline_config.environment: "HOMO"
    payline_config.log_path: /var/www/my_project/app/logs/testPayline.log

services:
    px_core_payline.service:
        class: pxCore\PaylineBundle\Model\Payline\Payline
        arguments: [%payline_config.merchant_id%, %payline_config.access_key%, %payline_config.proxy_host%, %payline_config.proxy_port%, %payline_config.proxy_login%, %payline_config.proxy_password%, %payline_config.environment%, %payline_config.log_path%]
